### ISSUE TITLE
Improve UX of next/previous

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog-react-rrweb-player#6]
If in the current state we're making use of previous/next recordings, and one of the two is not available, show the button but disabled. Currently if there's a next recording available but not a previous one we show only the next button which can be a bit confusing and visually does not look great.

We should however keep the logic that if neither next/previous is available, the buttons should be gone.

**Comment by macobo** [comment]
Ideally we'd also add some sort of autoplay functionality which automatically plays next as current one ends. :)

**Comment by paolodamico** [comment]
My thoughts exactly! Forgot to add the note here.

**Comment by paolodamico** [comment]
I think all the latest changes @rcmarron has done makes this obsolete, closing.
